### ISSUE TITLE
Pushpin not able to start

### ISSUE THREAD

**Issue by mersed** [fanout/pushpin#47227]
When i want to start pushpin I am getting following output

```
starting...
starting mongrel2 (http:3000)
starting m2adapter
starting zurl
starting pushpin-proxy
starting pushpin-handler
started
Traceback (most recent call last):
  File "/usr/local/bin/pushpin", line 59, in <module>
    runner.run(exedir, config_file, verbose)
  File "/usr/local/lib/pushpin/runner/runner.py", line 111, in run
    p.wait()
  File "/usr/local/lib/pushpin/runner/processmanager.py", line 90, in wait
    p.check()
  File "/usr/local/lib/pushpin/runner/processmanager.py", line 41, in check
    raise RuntimeError("process exited unexpectedly: %s" % self.name)
RuntimeError: process exited unexpectedly: m2adapter
```

I checked mongrel2 and i am able to run it without any kind of issues. I checked m2adapter logs within var/www/pushpin log directory and nothing usefull there:

```
[INFO] 2015-04-07 14:08:25.554 starting...
[INFO] 2015-04-07 14:09:19.096 starting...
[INFO] 2015-04-07 14:12:22.728 starting...
[INFO] 2015-04-07 15:06:56.012 starting...
[INFO] 2015-04-07 19:05:10.023 starting...
[INFO] 2015-04-07 19:13:03.515 starting...
[INFO] 2015-04-07 19:15:24.216 starting...
[INFO] 2015-04-07 19:15:57.014 starting...
[INFO] 2015-04-07 19:23:19.709 starting...
[INFO] 2015-04-07 19:28:20.920 starting...
[INFO] 2015-04-07 19:29:00.137 starting...
```

Any kind of additional configuration for m2adapter required?

**Comment by jkarneges** [comment]
Try running pushpin with --verbose. That'll put more info in the logs.

**Comment by mersed** [comment]
Tried with "verbose" same thing, i was not able to find any additional info within the logs.

Content of error_3000.log
```
Tue, 07 Apr 2015 23:37:30 GMT [INFO] (src/server.c:450) Starting 0MQ with 1 threads.
Tue, 07 Apr 2015 23:37:30 GMT [INFO] (src/request.c:58) MAX limits.header_count=1280
Tue, 07 Apr 2015 23:37:30 GMT [INFO] (src/connection.c:1176) MAX limits.content_length=20480, limits.buffer_size=4096, limits.connection_stack_size=32768, limits.client_read_retries=5
Tue, 07 Apr 2015 23:37:30 GMT [INFO] (src/connection.c:1182) MAX limits.proxy_read_retries=100, limits.proxy_read_retry_warn=10
Tue, 07 Apr 2015 23:37:30 GMT [INFO] (src/task/fd.c:153) MAX limits.fdtask_stack=102400
Tue, 07 Apr 2015 23:37:30 GMT [INFO] (src/handler.c:274) MAX allowing limits.handler_targets=128
Tue, 07 Apr 2015 23:37:30 GMT [INFO] (src/handler.c:360) Binding handler PUSH socket ipc://../../var/run/pushpin/pushpin-m2-out-3000 with identity: pushpin-m2-3000
Tue, 07 Apr 2015 23:37:30 GMT [INFO] (src/handler.c:386) Binding listener SUB socket ipc://../../var/run/pushpin/pushpin-m2-in-3000 subscribed to: pushpin-m2-3000
Tue, 07 Apr 2015 23:37:30 GMT [INFO] (src/control.c:437) Setting up control socket in at ipc://../../var/run/pushpin/pushpin-m2-control-3000
Tue, 07 Apr 2015 23:37:30 GMT [INFO] (src/mongrel2.c:301) -- Mongrel2/1.9.1 Running. Copyright (C) Zed A. Shaw. Licensed BSD
```

Content of m2adapter.log 
```
[INFO] 2015-04-07 23:37:30.110 starting...
```

Content of mongrel2_3000.log
```
Tue, 07 Apr 2015 23:37:30 GMT [INFO] (src/mime.c:49) MAX limits.mime_ext_len=128
Tue, 07 Apr 2015 23:37:30 GMT [INFO] (src/host.c:74) MAX limits.url_path=256, limits.host_name=256
Tue, 07 Apr 2015 23:37:30 GMT [INFO] (src/handler.c:413) MAX limits.handler_stack=102400
Tue, 07 Apr 2015 23:37:30 GMT [INFO] (src/config/config.c:86) Loaded handler 1:ipc://../../var/run/pushpin/pushpin-m2-out-3000:pushpin-m2-3000:ipc://../../var/run/pushpin/pushpin-m2-in-3000:pushpin-m2-3000
Tue, 07 Apr 2015 23:37:30 GMT [INFO] (src/config/config.c:228) Loaded route 1:/:handler for host 1:default
Tue, 07 Apr 2015 23:37:30 GMT [INFO] (src/config/config.c:324) Loaded 1 hosts for server 1:default_3000
Tue, 07 Apr 2015 23:37:30 GMT [INFO] (src/server.c:624) LOADING Handler ipc://../../var/run/pushpin/pushpin-m2-out-3000
Tue, 07 Apr 2015 23:37:30 GMT [ERROR] (src/unixy.c:123: errno: No such file or directory) Failed to open PID file ../../var/run/pushpin/mongrel2_3000.pid for reading.
Tue, 07 Apr 2015 23:37:30 GMT [INFO] (src/unixy.c:161) No previous mongrel2 running, continuing on.
Tue, 07 Apr 2015 23:37:30 GMT [INFO] (src/mongrel2.c:228) All loaded up, time to turn into a server.
Tue, 07 Apr 2015 23:37:30 GMT [INFO] (src/mongrel2.c:229) -- Starting Mongrel2/1.9.1. Copyright (C) Zed A. Shaw. Licensed BSD.

Tue, 07 Apr 2015 23:37:30 GMT [INFO] (src/mongrel2.c:230) -- Look in ../../var/log/pushpin/error_3000.log for startup messages and errors.
Tue, 07 Apr 2015 23:37:30 GMT [INFO] (src/unixy.c:105) Now running as UID:0, GID:0
```

**Comment by jkarneges** [comment]
Try running m2adapter directly:

    m2adapter --config=/var/run/pushpin/m2adapter.conf --verbose

**Comment by mersed** [comment]
Indeed, that added one more line, but honestly it does not make a lot of sense to me. 

```
[INFO] 2015-04-07 23:56:30.327 starting...
m2adapter: ../../qzmq/src/qzmqsocket.cpp:185: void QZmq::set_hwm(void*, int): Assertion `ret == 0' failed.
Aborted (core dumped)
```

**Comment by jkarneges** [comment]
Wow, that should really never happen.

What is your OS? Did you install zeromq from a prebuilt package? Is pushpin from a package as well, or source?

**Comment by mersed** [comment]
OS: Ubuntu 14.04.2 LTS

I installed pushpin from building from source (basically i followed this guide with one difference)
https://github.com/fanout/pushpin/wiki/Install

Within that page it says:
```
If you're using a recent version of Debian or Ubuntu, then all dependencies can be installed via package management:

sudo apt-get install pkg-config libqt4-dev libqca2-dev \
  libqca2-plugin-ossl libqjson-dev libzmq3-dev python-zmq \
  python-setproctitle python-jinja2 python-tnetstring \
  mongrel2-core zurl
```

mongrel2-core by default do not exists, i installed mongrel manually following their installation guide:
http://mongrel2.org/wiki/quick_start.html

Using their guide installation i installed zeromq (building from source as well), but i installed zeromq-2.1.7 version. Is there any kind of requirements based on zmq version?

**Comment by jkarneges** [comment]
Yeah definitely remove that compiled version (2.1 is extremely old) and use the version from Ubuntu instead (libzmq3-dev). Mongrel2 should compile fine against recent libzmq.

**Comment by mersed** [comment]
Well that is the issue. I tried last version of zmq with mongrel and had some issues (because of that i decide to use really old one). Then i will try not latest one, but not something ancient as well. Thank you

**Comment by mersed** [comment]
Works perfectly with things you suggested. Thank you

**Comment by jkarneges** [comment]
whew :)

**Comment by johnjelinek** [comment]
@jkarneges: I'm running into this issue too with `v1.3.3`. Here are the install steps I'm using https://gist.github.com/johnjelinek/5532e09d53edc937b058. I'm using debian:unstable because that one has `python-sortedcontainers` and all of the other packages mentioned in the wiki install guide.

Here's what I see pushpin starts:
```
# ./pushpin
Fri, 17 Jul 2015 02:53:32 GMT [ERROR] (errno: Inappropriate ioctl for device) getlogin failed and no LOGNAME env variable, how'd you do that?
starting...
starting mongrel2 (http:7999)
starting m2adapter
starting zurl
starting pushpin-proxy
starting pushpin-handler
started
Traceback (most recent call last):
  File "./pushpin", line 59, in <module>
    runner.run(exedir, config_file, verbose)
  File "/pushpin/runner/runner.py", line 111, in run
    p.wait()
  File "/pushpin/runner/processmanager.py", line 90, in wait
    p.check()
  File "/pushpin/runner/processmanager.py", line 41, in check
    raise RuntimeError("process exited unexpectedly: %s" % self.name)
RuntimeError: process exited unexpectedly: mongrel2 (http:7999)
```

**Comment by jkarneges** [comment]
Looks like mongrel2 died. Most common reason is port in-use or if it thinks it's already running. To investigate, try running it manually in the foreground:

    mongrel2 runner/run/mongrel2.sqlite default_7999

**Comment by jkarneges** [comment]
Btw you still need ``python-blist`` with version 1.3.3. There hasn't been a release yet with the sortedcontainers change. If you want to test that, use the develop branch instead of the v1.3.3 tag.

**Comment by jkarneges** [comment]
Released v1.4.0 with the change.

**Comment by johnjelinek** [comment]
so, no blist is needed now, right?

**Comment by jkarneges** [comment]
Correct.
